<a href="https://colab.research.google.com/github/kouib123/Creating-an-Incremental-Loading-Versus-Flush-and-Fill-on-SQL-Server-For-ETL-Processing/blob/master/FIFA_2022_Match_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
# This is formatted as code
```

# FIFA 2022 World Cup Prediction

In [2]:
#  Import Pyton Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

'''
Pre-process raw data from international_matches.csv which contains all international match results.
Introduce attributes such as winning counts, goal difference, etc. for prediction task later.
Author: **kouib123**

> Indented block



'''

In [3]:
# Importing team datasets:
team_names = ['Qatar','Ecuador','Senegal','Netherlands',
              'England','Iran','United States','Wales',
              'Argentina','Saudi Arabia','Mexico', 'Poland',
              'France','Australia','Dennmark','Tunisia',
              'Spain','Costa Rica','Germany','Japan',
              'Belgium','Canada','Morocco','Croatia',
              'Brazil','Serbia','Switzerland','Cameroon',
              'Portugal','Ghana','Uruguay','South Korea']

In [9]:
# Loading the  datasets:
history = pd.read_csv('/content/intel_matches.csv')
rankings = pd.read_csv('/content/fifa_rankings.csv')
history
rankings

,rank,country_full,country_abrv,total_points,previous_points,rank_change,cur_year_avg,cur_year_avg_weighted,last_year_avg,last_year_avg_weighted,two_year_ago_avg,two_year_ago_weighted,three_year_ago_avg,three_year_ago_weighted,confederation,rank_date,year
0,1,Germany,GER,0.0,57,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,8/8/1993,1993
1,2,Italy,ITA,0.0,57,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,8/8/1993,1993
2,3,Switzerland,SUI,0.0,50,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,8/8/1993,1993
3,4,Sweden,SWE,0.0,55,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,8/8/1993,1993
4,5,Argentina,ARG,0.0,51,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CONMEBOL,8/8/1993,1993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57788,206,Anguilla,AIA,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CONCACAF,7/6/2018,2018
57789,206,Bahamas,BAH,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CONCACAF,7/6/2018,2018
57790,206,Eritrea,ERI,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CAF,7/6/2018,2018
57791,206,Somalia,SOM,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CAF,7/6/2018,2018
57792,206,Tonga,TGA,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OFC,7/6/2018,2018